### ISSUE TITLE
Transfer NPM package ownership?

### ISSUE THREAD

**Issue by milesj** [gsf/rut#1]
@gsf  I tried sending an email, but the email associated with (https://www.npmjs.com/package/rut) doesn't seem to work anymore.

Anyways, I would love to use the `rut` package name. This repo seems deprecated and unused for the most part, so if you agree in transferring, that would be amazing. Instructions here: https://docs.npmjs.com/transferring-a-package-from-a-user-account-to-another-user-account

Cheers,
Miles

**Comment by gsf** [comment]
Sure, I only ask that you leave the existing versions up so my old projects can still pull them. Is milesj your npm name as well?

**Comment by milesj** [comment]
@gsf Yeah that's no problem. I don't believe NPM allows overriding of existing versions anyways.

And yeah, `milesj` is the same name. https://www.npmjs.com/~milesj

**Comment by gsf** [comment]
Sweet. I've added you to the maintainer list.

**Comment by milesj** [comment]
@gsf Thanks so much! I tagged a v0.1.0 as to not collide with your previous versions.
